# Generated by Django 3.2.5 on 2021-08-08 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_alter_userprofile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Small Package', 'Small Package'), ('Small Box', 'Small Box'), ('medium', 'Medium Box'), ('large', 'Large Box')], max_length=30)),
                ('destination_address', models.CharField(max_length=100)),
                ('date_made', models.DateTimeField(default=datetime.datetime(2021, 8, 8, 17, 14, 41, 979287))),
                ('date_delivered', models.DateTimeField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='profiles.userprofile')),
                ('delivery_guy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_guy', to='profiles.userprofile')),
            ],
        ),
    ]
