# Generated by Django 3.2.5 on 2021-08-08 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210808_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_made',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 17, 18, 42, 554798)),
        ),
    ]
