# Generated by Django 3.2.5 on 2021-08-08 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_city'),
        ('orders', '0003_alter_order_date_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_made',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 17, 19, 6, 347802)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_guy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_guy', to='profiles.userprofile'),
        ),
    ]
