# Generated by Django 3.2.5 on 2021-08-08 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210808_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_made',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 18, 43, 17, 58897)),
        ),
    ]
