# Generated by Django 3.2.5 on 2021-08-08 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_date_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_made',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 19, 32, 20, 494379)),
        ),
    ]
