# Generated by Django 3.2.5 on 2021-08-14 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210814_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_made',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 3, 4, 59, 310833)),
        ),
    ]
