# Generated by Django 3.2.5 on 2021-08-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('wheeldeal_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('is_complete', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='profile_images')),
                ('is_client', models.BooleanField(default=True)),
                ('is_deliveryman', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('price_for_delivery', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wheeldeal_auth.wheeldealuser')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.city')),
            ],
        ),
    ]
