# Generated by Django 3.2.5 on 2021-08-14 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='is_accepted',
            new_name='is_approved',
        ),
    ]
